### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by inside83** [viper3400/RegExTractor#11]
I just installed and got this
![image](https://user-images.githubusercontent.com/10822610/57489674-0cbff880-72b7-11e9-840b-b763169f6724.png)

**Comment by viper3400** [comment]
Hi @inside83 

This is an issue of the Notepad++ NppRegExTractor plugin, not directly an issue of RegExTractor itself. 

Plugin Manager and plugin system of Notepad++ has been redesigned and it seems there are some breaking changes. NppRegExTractor may not be usable any longer. See https://github.com/viper3400/NppRegExTractor/issues/5.

As the plugin is just a wrapper for https://github.com/viper3400/RegExTractor, please consider using the native windows app in this repository here.

Do you use the plugin for your needs or did you just want to try out?

**Comment by inside83** [comment]
I just wanted to try out and couldn't even use the plugin.

**Comment by viper3400** [comment]
@inside83, if you'd like to try out, please use the stable Windows version https://github.com/viper3400/RegExTractor/releases/download/1.3.4/RegExTractor_V1.3.4.zip. It has the same functionalities. 
Let me know, if you still need the plugin version.

**Comment by gurikbal** [comment]
this issue is just fixed in https://github.com/viper3400/NppRegExTractor/pull/6
and you can download English Version here :-

[NppRegExTractorPlugin_x86.zip](https://github.com/viper3400/RegExTractor/files/3773310/NppRegExTractorPlugin_x86.zip)
[NppRegExTractorPlugin_x64.zip](https://github.com/viper3400/RegExTractor/files/3773311/NppRegExTractorPlugin_x64.zip)

**Comment by viper3400** [comment]
Solved with version 2.1 available in NPP plugin manager
